# Generated by Django 4.2.6 on 2023-12-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donhang',
            fields=[
                ('madonhang', models.CharField(db_column='MaDonHang', max_length=15, primary_key=True, serialize=False)),
                ('tinhtrang', models.IntegerField(blank=True, db_column='TinhTrang', null=True)),
                ('ngaytaodon', models.DateField(db_column='NgayTaoDon')),
                ('tongtien', models.IntegerField(blank=True, db_column='TongTien', null=True)),
                ('coupon', models.CharField(blank=True, db_column='Coupon', max_length=8, null=True)),
            ],
            options={
                'db_table': 'donhang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('sodienthoai', models.CharField(db_column='SoDienThoai', max_length=10, primary_key=True, serialize=False)),
                ('diemtichluy', models.IntegerField(db_column='DiemTichLuy')),
                ('ten', models.CharField(blank=True, db_column='Ten', max_length=1, null=True)),
                ('duong', models.CharField(blank=True, db_column='Duong', max_length=50, null=True)),
                ('quanhuyen', models.CharField(blank=True, db_column='QuanHuyen', max_length=50, null=True)),
                ('thanhpho', models.CharField(blank=True, db_column='ThanhPho', max_length=50, null=True)),
            ],
            options={
                'db_table': 'khachhang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nhanvienxuatdonhang',
            fields=[
                ('manhanvien', models.OneToOneField(db_column='MaNhanVien', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='nhanvien.nhanvien')),
                ('thoigianxuly', models.DateField(db_column='ThoiGianXuLy')),
            ],
            options={
                'db_table': 'nhanvienxuatdonhang',
                'managed': False,
            },
        ),
    ]
