# Generated by Django 4.2.6 on 2023-12-03 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0004_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uudai',
            fields=[
                ('mauudai', models.CharField(db_column='MaUuDai', max_length=8, primary_key=True, serialize=False)),
                ('sotientoithieu', models.IntegerField(blank=True, db_column='SoTienToiThieu', null=True)),
                ('tinhtrang', models.IntegerField(blank=True, db_column='TinhTrang', null=True)),
                ('batdau', models.DateField(db_column='BatDau')),
                ('ketthuc', models.DateField(blank=True, db_column='KetThuc', null=True)),
            ],
            options={
                'db_table': 'uudai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('mucgiamgia', models.IntegerField(blank=True, db_column='MucGiamGia', null=True)),
                ('mucgiamgiamax', models.IntegerField(blank=True, db_column='MucGiamGiaMax', null=True)),
                ('mauudai', models.OneToOneField(db_column='MaUuDai', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='nhanvien.uudai')),
            ],
            options={
                'db_table': 'coupon',
                'managed': False,
            },
        ),
    ]
